use crate::engine::AudioEngine;
use crate::ipc::{Command, Response, TrackParameters};

impl AudioEngine {
    pub fn handle_track_control_command(&mut self, command: Command) -> Option<Response> {
        match command {
            Command::SetGain { track, gain } => {
                self.set_gain(track, gain);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: Some(gain),
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetVolume { track, volume } => {
                self.set_volume(track, volume);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: Some(volume),
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetMute { track, mute } => {
                self.set_mute(track, mute);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: Some(mute),
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetSolo { track, solo } => {
                self.set_solo(track, solo);
                
                // Get all track mute and solo states after solo change
                let router = self.router.lock().unwrap();
                let mut track_params = Vec::new();
                
                for i in 0..router.tracks.len() {
                    if let Some(t) = router.get_track(i) {
                        track_params.push(TrackParameters {
                            track: i,
                            gain: None,
                            volume: None,
                            mute: Some(t.mute),
                            solo: Some(t.solo),
                            pan: None,
                            route_to_master: None,
                            route_to_subgroups: None,
                            pad_enabled: None,
                            hpf_enabled: None,
                            phase_inverted: None,
                            pfl_enabled: None,
                            compressor_enabled: None,
                            compressor_threshold_db: None,
                            compressor_ratio: None,
                            compressor_attack_ms: None,
                            compressor_release_ms: None,
                            gate_enabled: None,
                            gate_threshold_db: None,
                            gate_range_db: None,
                            gate_attack_ms: None,
                            gate_release_ms: None,
                            eq_enabled: None,
                            eq_low: None,
                            eq_low_mid: None,
                            eq_high_mid: None,
                            eq_high: None,
                            parametric_eq_enabled: None,
                            eq_filters: None,
                            aux_sends: None,
                            file_name: None,
                            file_artist: None,
                            file_title: None,
                            is_stereo: None,
                            fft_data: None,
                            inserts: None,
                        });
                    }
                }
                drop(router);
                
                Some(Response::ParametersChanged {
                    tracks: Some(track_params),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetRouteToMaster { track, route } => {
                self.set_route_to_master(track, route);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: Some(route),
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetPan { track, pan } => {
                self.set_pan(track, pan);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: Some(pan),
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackPad { track, enabled } => {
                self.set_pad(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: Some(enabled),
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackHPF { track, enabled } => {
                self.set_hpf(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: Some(enabled),
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackPhaseInvert { track, enabled } => {
                self.set_phase_invert(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: Some(enabled),
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackPFL { track, enabled } => {
                self.set_pfl(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: Some(enabled),
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackRouteToSubgroup {
                track,
                subgroup,
                route,
            } => {
                self.set_track_route_to_subgroup(track, subgroup, route);
                
                // Get updated routing list
                let route_to_subgroups = if let Ok(router) = self.router.try_lock() {
                    if track < router.tracks.len() {
                        router.tracks[track].route_to_subgroups.clone()
                    } else {
                        vec![]
                    }
                } else {
                    vec![]
                };
                
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: Some(route_to_subgroups),
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            _ => None,
        }
    }
}
