use crate::engine::AudioEngine;
use crate::ipc::{Command, Response, TrackParameters, AuxSendData};

impl AudioEngine {
    pub fn handle_track_effects_command(&mut self, command: Command) -> Option<Response> {
        match command {
            Command::SetCompressor {
                track,
                enabled,
                threshold,
                ratio,
                attack,
                release,
            } => {
                self.set_compressor(track, enabled, threshold, ratio, attack, release);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: Some(enabled),
                        compressor_threshold_db: Some(threshold),
                        compressor_ratio: Some(ratio),
                        compressor_attack_ms: Some(attack),
                        compressor_release_ms: Some(release),
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetGate {
                track,
                enabled,
                threshold,
                range,
                attack,
                release,
            } => {
                self.set_gate(track, enabled, threshold, range, attack, release);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: Some(enabled),
                        gate_threshold_db: Some(threshold),
                        gate_range_db: Some(range),
                        gate_attack_ms: Some(attack),
                        gate_release_ms: Some(release),
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetEQ {
                track,
                low,
                low_mid,
                high_mid,
                high,
            } => {
                self.set_eq(track, low, low_mid, high_mid, high);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: Some(low),
                        eq_low_mid: Some(low_mid),
                        eq_high_mid: Some(high_mid),
                        eq_high: Some(high),
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetEQEnabled { track, enabled } => {
                self.set_eq_enabled(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: Some(enabled),
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetParametricEQFilters { track, filters } => {
                self.set_parametric_eq_filters(track, &filters);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: Some(filters),
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetParametricEQEnabled { track, enabled } => {
                self.set_parametric_eq_enabled(track, enabled);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: Some(enabled),
                        eq_filters: None,
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::ClearParametricEQ { track } => {
                self.clear_parametric_eq(track);
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: Some(vec![]),
                        aux_sends: None,
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            Command::SetTrackAuxSend {
                track,
                aux,
                level,
                pre_fader,
                muted,
            } => {
                self.set_track_aux_send(track, aux, level, pre_fader, muted);
                
                // Get updated aux sends for this track and convert to AuxSendData
                let aux_sends = if let Ok(router) = self.router.try_lock() {
                    if track < router.tracks.len() {
                        router.tracks[track].aux_sends.iter().map(|send| AuxSendData {
                            level: send.level,
                            pre_fader: send.pre_fader,
                            muted: send.muted,
                        }).collect()
                    } else {
                        vec![]
                    }
                } else {
                    vec![]
                };
                
                Some(Response::ParametersChanged {
                    tracks: Some(vec![TrackParameters {
                        track,
                        gain: None,
                        volume: None,
                        mute: None,
                        solo: None,
                        pan: None,
                        route_to_master: None,
                        route_to_subgroups: None,
                        pad_enabled: None,
                        hpf_enabled: None,
                        phase_inverted: None,
                        pfl_enabled: None,
                        compressor_enabled: None,
                        compressor_threshold_db: None,
                        compressor_ratio: None,
                        compressor_attack_ms: None,
                        compressor_release_ms: None,
                        gate_enabled: None,
                        gate_threshold_db: None,
                        gate_range_db: None,
                        gate_attack_ms: None,
                        gate_release_ms: None,
                        eq_enabled: None,
                        eq_low: None,
                        eq_low_mid: None,
                        eq_high_mid: None,
                        eq_high: None,
                        parametric_eq_enabled: None,
                        eq_filters: None,
                        aux_sends: Some(aux_sends),
                        file_name: None,
                        file_artist: None,
                        file_title: None,
                        is_stereo: None,
                        fft_data: None,
                        inserts: None,
                    }]),
                    subgroups: None,
                    auxes: None,
                    master: None,
                })
            }
            _ => None,
        }
    }
}
